### ISSUE TITLE
获取系统信息的方法

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/CTP#16]
Netlink
ioctl
proc

**Comment by Veiasai** [comment]
Netlink用到systemcall socket
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 3
第三个参数为netlink所支持的协议

ioctl就是一个systemcall，用来操作某些硬件设备

proc是虚拟文件系统，挂载了各种进程信息

**Comment by Veiasai** [comment]
https://blog.csdn.net/zcabcd123/article/details/8272656

https://blog.csdn.net/luckyapple1028/article/details/50839395

**Comment by Gusabary** [comment]
插眼
