### ISSUE TITLE
获取文件信息

### ISSUE THREAD

**Issue by Veiasai** [Veiasai/CTP#20]
1. lsof

selinux太重量级，看了看，使用起来还是很麻烦。

我们只需要lsof这样的功能就行了。

**Comment by Gusabary** [comment]
插眼

**Comment by Bert-Z** [comment]
pin

**Comment by Bert-Z** [comment]
查到的一些system call的作用和分类，可以作为参考
https://www.ibm.com/developerworks/cn/linux/kernel/syscall/part1/appendix.html
https://blog.csdn.net/sinat_26227857/article/details/44244433

**Comment by Veiasai** [comment]
/proc/{pid}/fd
